

services:
  nginx:
    build:
      context: ./nginx
    container_name: "nginx_cont"
    ports:
     - "80:80"

    restart: always
    depends_on: 
      - django
    networks:
      - notes-app
  db:
    image: mysql
    container_name: "db_cont"


    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root
    volumes: 
     - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - notes-app
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost", "-uroot","-proot"]
      interval: 10s
      retries: 5
      start_period: 60s
  django:
    build:
      context: .
    container_name: "django_cont"
    command: sh -c "python manage.py migrate --no-input && gunicorn notesapp.wsgi  --bind 0.0.0.0:8000"
    env_file:
      - ".env"
    restart: always
    networks:
      - notes-app
    ports:
     - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      retries: 5
      start_period: 60s
    depends_on:
      - db

networks:
  notes-app:

    

